### ISSUE TITLE
Allow project-specifc sync rules

### ISSUE THREAD

**Issue by abhchand** [abhchand/ghtp#1]
Allow sync rules to be specified per project

e.g.

```yml
sync:
  rules:
    - if_has: "foo"
      then_set: Bar

  projects:
    "project a":
      rules:
        - if_has: "foo"
          then_set: Bar2
```
